name = "medal-bypass-api"
compatibility_date = "2024-01-01"

[build]
command = "bun build ./src/index.ts --outfile=dist/index.js --minify"
watch_dir = "src"

[build.upload]
format = "modules"
main = "index.js"
dir = "dist"

[vars]
ENVIRONMENT = "production"

[[routes]]
pattern = "medal.xvh.lol"
custom_domain = true

[miniflare]
kv_persist = true
cache_persist = true

[env.development]
name = "medal-api-dev"
vars = { ENVIRONMENT = "development" }

[env.production]
name = "medal-api-prod"
vars = { ENVIRONMENT = "production" }